### PR TITLE
Upgrade babel-eslint and @babel/eslint-plugin

### PR DESCRIPTION
**Pull request by aovens-coursera**
These are out of date

### CODE REVIEW

**Comment by aovens-coursera** [comment]
I'd be scared to touch any of the others, I don't want to introduce new rules

**Comment by gagoar** [comment]
@aovens-coursera that's a safe bet! 😄

**Comment by ppaskaris-coursera** [comment]
> @aovens-coursera that's a safe bet! 😄

flappy-cat

**Comment by ppaskaris-coursera** [comment]
I am merging this on your behalf

**Pull request merged**
